server:
  port: 8089
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: aa111111
    username: utils_user
    url: jdbc:mysql://localhost:3306/utils_db?useUnicode=true&useSSL=false&characterEncoding=UTF-8
  redis:
    #默认端口为0,redis一般有16个数据库
    database: 0
    #服务器地址
    host: localhost
    #服务器连接端口：默认6379
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 1000000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池中的最大空闲连接
        max-idle: 30
        # 连接池中的最小空闲连接
        min-idle: 1
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1

#打印SQL
logging:
  level:
  #开发环境为debug
   com.zimo.mybaties: debug
mybatis:
  #配置mapper文件所在地，在 resources 目录下的mapper目录的*xml文件
  mapper-locations: classpath:mybatis/mapper/*.xml
  #配置文件
  config-location: classpath:mybatis/mybatis-config.xml
  #对应实体类的路径
  type-aliases-package: com.zimo.mybaties.model






